### ISSUE TITLE
Missing RET case for JMP instruction.

### ISSUE THREAD

**Issue by theolepage** [P-E-P/LC3-Emu#2]
According to the documentation of the LC-3 ISA, the RET instruction is a special case of the JMP instruction which allows returning from a subroutine.

If all the three bits of the BaseR are set to 1, we have to load the PC with the value of the register R7.

---

Current JMP handler:
https://github.com/P-E-P/LC3-Emu/blob/d1495f2af8091bd0e7b636f616b3837f55e05739/src/lc3.c#L157-L159

Corrected JMP handler:
```c
case OP_JMP:
    if (BR_OP(ins) == 0x7) // RET
    {
        reg[R_PC] = reg[R_R7];
    }
    else // JMP
    {
        reg[R_PC] = BR_OP(ins);
    }
    break;
```

**Comment by P-E-P** [comment]
The RET instruction has been added in commit  #ef7211a9117bed1665d94ebd15baf11048fe7df0
